load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")
load(":build_defs.bzl", "documentation")

documentation(
    name = "warnings_docs",
    bin = ":go_default_binary",
    markdown = "WARNINGS.md",
    textproto = "warnings.textproto",
)

go_binary(
    name = "go_default_binary",
    embed = [":docs_lib"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "docs_lib",
    srcs = ["docs.go"],
    importpath = "github.com/bazelbuild/buildtools/warn/docs",
    visibility = ["//visibility:private"],
    deps = [
        "//warn",
        "//warn/docs/proto",
        "@com_github_golang_protobuf//proto:go_default_library",
    ],
)

go_test(
    name = "docs_test",
    size = "small",
    srcs = ["docs_test.go"],
    data = [
        "warnings.textproto",
        ":warnings_docs",
        "//:warnings",
    ],
    embed = [":docs_lib"],
    deps = [
        "//testutils",
        "//warn",
    ],
)
