// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.0
// source: deps_proto/deps.proto

package deps_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dependency_Kind int32

const (
	Dependency_EXPLICIT   Dependency_Kind = 0
	Dependency_IMPLICIT   Dependency_Kind = 1
	Dependency_UNUSED     Dependency_Kind = 2
	Dependency_INCOMPLETE Dependency_Kind = 3
)

// Enum value maps for Dependency_Kind.
var (
	Dependency_Kind_name = map[int32]string{
		0: "EXPLICIT",
		1: "IMPLICIT",
		2: "UNUSED",
		3: "INCOMPLETE",
	}
	Dependency_Kind_value = map[string]int32{
		"EXPLICIT":   0,
		"IMPLICIT":   1,
		"UNUSED":     2,
		"INCOMPLETE": 3,
	}
)

func (x Dependency_Kind) Enum() *Dependency_Kind {
	p := new(Dependency_Kind)
	*p = x
	return p
}

func (x Dependency_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Dependency_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_deps_proto_deps_proto_enumTypes[0].Descriptor()
}

func (Dependency_Kind) Type() protoreflect.EnumType {
	return &file_deps_proto_deps_proto_enumTypes[0]
}

func (x Dependency_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Dependency_Kind) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Dependency_Kind(num)
	return nil
}

// Deprecated: Use Dependency_Kind.Descriptor instead.
func (Dependency_Kind) EnumDescriptor() ([]byte, []int) {
	return file_deps_proto_deps_proto_rawDescGZIP(), []int{1, 0}
}

type SourceLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Line          *int32                 `protobuf:"varint,2,opt,name=line" json:"line,omitempty"`
	Column        *int32                 `protobuf:"varint,3,opt,name=column" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceLocation) Reset() {
	*x = SourceLocation{}
	mi := &file_deps_proto_deps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceLocation) ProtoMessage() {}

func (x *SourceLocation) ProtoReflect() protoreflect.Message {
	mi := &file_deps_proto_deps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceLocation.ProtoReflect.Descriptor instead.
func (*SourceLocation) Descriptor() ([]byte, []int) {
	return file_deps_proto_deps_proto_rawDescGZIP(), []int{0}
}

func (x *SourceLocation) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *SourceLocation) GetLine() int32 {
	if x != nil && x.Line != nil {
		return *x.Line
	}
	return 0
}

func (x *SourceLocation) GetColumn() int32 {
	if x != nil && x.Column != nil {
		return *x.Column
	}
	return 0
}

type Dependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Kind          *Dependency_Kind       `protobuf:"varint,2,req,name=kind,enum=blaze_deps.Dependency_Kind" json:"kind,omitempty"`
	Location      []*SourceLocation      `protobuf:"bytes,3,rep,name=location" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_deps_proto_deps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_deps_proto_deps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_deps_proto_deps_proto_rawDescGZIP(), []int{1}
}

func (x *Dependency) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *Dependency) GetKind() Dependency_Kind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return Dependency_EXPLICIT
}

func (x *Dependency) GetLocation() []*SourceLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type Dependencies struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Dependency       []*Dependency          `protobuf:"bytes,1,rep,name=dependency" json:"dependency,omitempty"`
	RuleLabel        *string                `protobuf:"bytes,2,opt,name=rule_label,json=ruleLabel" json:"rule_label,omitempty"`
	Success          *bool                  `protobuf:"varint,3,opt,name=success" json:"success,omitempty"`
	ContainedPackage []string               `protobuf:"bytes,4,rep,name=contained_package,json=containedPackage" json:"contained_package,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Dependencies) Reset() {
	*x = Dependencies{}
	mi := &file_deps_proto_deps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependencies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependencies) ProtoMessage() {}

func (x *Dependencies) ProtoReflect() protoreflect.Message {
	mi := &file_deps_proto_deps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependencies.ProtoReflect.Descriptor instead.
func (*Dependencies) Descriptor() ([]byte, []int) {
	return file_deps_proto_deps_proto_rawDescGZIP(), []int{2}
}

func (x *Dependencies) GetDependency() []*Dependency {
	if x != nil {
		return x.Dependency
	}
	return nil
}

func (x *Dependencies) GetRuleLabel() string {
	if x != nil && x.RuleLabel != nil {
		return *x.RuleLabel
	}
	return ""
}

func (x *Dependencies) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *Dependencies) GetContainedPackage() []string {
	if x != nil {
		return x.ContainedPackage
	}
	return nil
}

var File_deps_proto_deps_proto protoreflect.FileDescriptor

const file_deps_proto_deps_proto_rawDesc = "" +
	"\n" +
	"\x15deps_proto/deps.proto\x12\n" +
	"blaze_deps\"P\n" +
	"\x0eSourceLocation\x12\x12\n" +
	"\x04path\x18\x01 \x02(\tR\x04path\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x03 \x01(\x05R\x06column\"\xc9\x01\n" +
	"\n" +
	"Dependency\x12\x12\n" +
	"\x04path\x18\x01 \x02(\tR\x04path\x12/\n" +
	"\x04kind\x18\x02 \x02(\x0e2\x1b.blaze_deps.Dependency.KindR\x04kind\x126\n" +
	"\blocation\x18\x03 \x03(\v2\x1a.blaze_deps.SourceLocationR\blocation\">\n" +
	"\x04Kind\x12\f\n" +
	"\bEXPLICIT\x10\x00\x12\f\n" +
	"\bIMPLICIT\x10\x01\x12\n" +
	"\n" +
	"\x06UNUSED\x10\x02\x12\x0e\n" +
	"\n" +
	"INCOMPLETE\x10\x03\"\xac\x01\n" +
	"\fDependencies\x126\n" +
	"\n" +
	"dependency\x18\x01 \x03(\v2\x16.blaze_deps.DependencyR\n" +
	"dependency\x12\x1d\n" +
	"\n" +
	"rule_label\x18\x02 \x01(\tR\truleLabel\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12+\n" +
	"\x11contained_package\x18\x04 \x03(\tR\x10containedPackageB*\n" +
	"(com.google.devtools.build.lib.view.proto"

var (
	file_deps_proto_deps_proto_rawDescOnce sync.Once
	file_deps_proto_deps_proto_rawDescData []byte
)

func file_deps_proto_deps_proto_rawDescGZIP() []byte {
	file_deps_proto_deps_proto_rawDescOnce.Do(func() {
		file_deps_proto_deps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deps_proto_deps_proto_rawDesc), len(file_deps_proto_deps_proto_rawDesc)))
	})
	return file_deps_proto_deps_proto_rawDescData
}

var file_deps_proto_deps_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_deps_proto_deps_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_deps_proto_deps_proto_goTypes = []any{
	(Dependency_Kind)(0),   // 0: blaze_deps.Dependency.Kind
	(*SourceLocation)(nil), // 1: blaze_deps.SourceLocation
	(*Dependency)(nil),     // 2: blaze_deps.Dependency
	(*Dependencies)(nil),   // 3: blaze_deps.Dependencies
}
var file_deps_proto_deps_proto_depIdxs = []int32{
	0, // 0: blaze_deps.Dependency.kind:type_name -> blaze_deps.Dependency.Kind
	1, // 1: blaze_deps.Dependency.location:type_name -> blaze_deps.SourceLocation
	2, // 2: blaze_deps.Dependencies.dependency:type_name -> blaze_deps.Dependency
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_deps_proto_deps_proto_init() }
func file_deps_proto_deps_proto_init() {
	if File_deps_proto_deps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deps_proto_deps_proto_rawDesc), len(file_deps_proto_deps_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deps_proto_deps_proto_goTypes,
		DependencyIndexes: file_deps_proto_deps_proto_depIdxs,
		EnumInfos:         file_deps_proto_deps_proto_enumTypes,
		MessageInfos:      file_deps_proto_deps_proto_msgTypes,
	}.Build()
	File_deps_proto_deps_proto = out.File
	file_deps_proto_deps_proto_goTypes = nil
	file_deps_proto_deps_proto_depIdxs = nil
}
